version: '3'
services:
  nestjs:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - reactjs

  reactjs:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - '5173:5173'
