name: API lint and test

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        working-directory: api
        run: npm install

      - name: Lint
        working-directory: api
        run: npm run lint

      - name: Tests
        working-directory: api
        run: npm run test
