name: Lint and Test

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'client/**'
  pull_request:
    paths:
      - 'api/**'
      - 'client/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Lint and test NestJS app
        if: ${{ contains(github.event.commits[0].added, 'api/') || contains(github.event.commits[0].modified, 'api/') }}
        working-directory: api
        run: |
          npm install
          npm run lint
          npm test

      - name: Lint and test ReactJS app
        if: ${{ contains(github.event.commits[0].added, 'client/') || contains(github.event.commits[0].modified, 'client/') }}
        working-directory: client
        run: |
          npm install
          npm run lint
          npm test
